# -*- coding: utf-8 -*-
"""COD_SEPM(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcpYXf_yMSF1RwjAxSRqsX3oMj0brqBx
"""

from google.colab import files

print("Upload Original Image")
orig = files.upload()

original_file = list(orig.keys())[0]
print("Original:", original_file)

print("Upload Crop Image")
crop = files.upload()

crop_file = list(crop.keys())[0]
print("Crop:", crop_file)

print("Upload Compression Image")
comp = files.upload()

compression_file = list(comp.keys())[0]
print("Compression:", compression_file)

print("Upload Screenshot Image")
ss = files.upload()

screenshot_file = list(ss.keys())[0]
print("Screenshot:", screenshot_file)

print("Upload Text Overlay Image")
txt = files.upload()

text_file = list(txt.keys())[0]
print("Text Overlay:", text_file)

print("Upload Noise Image")
noi = files.upload()

noise_file = list(noi.keys())[0]
print("Noise:", noise_file)

image_paths = {
    "Original": "000000356387 (2).jpg",
    "Crop": "000000356387 (3).jpg",
    "Compression": "000000356387 (4).jpg",
    "Screenshot": "000000356387 (5).jpg",
    "Text Overlay": "000000356387 (6).jpg",
    "Noise": "000000356387 (7).jpg"
}

import cv2
import matplotlib.pyplot as plt

images = {}

for name, path in image_paths.items():

    img = cv2.imread(path)

    if img is None:
        print(f"Failed to load: {path}")
        continue

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    images[name] = img

print("Loaded:", len(images), "images")

for name in images:
    print(name)

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams.update({
    'font.size':14,
    'axes.titlesize':18,
    'axes.labelsize':14,
    'legend.fontsize':12
})

for name, img in images.items():

    mean_rgb = np.mean(img, axis=(0,1))
    std_rgb = np.std(img, axis=(0,1))

    plt.figure(figsize=(10,6))

    colors = [
        ('Red', '#e63946'),
        ('Green', '#2a9d8f'),
        ('Blue', '#457b9d')
    ]

    for i,(label,color) in enumerate(colors):

        hist = cv2.calcHist(
            [img],
            [i],
            None,
            [256],
            [0,256]
        )

        plt.plot(
            hist,
            color=color,
            linewidth=3,
            label=label
        )

    stats_text = (
        f"Mean RGB\n"
        f"R={mean_rgb[0]:.1f}\n"
        f"G={mean_rgb[1]:.1f}\n"
        f"B={mean_rgb[2]:.1f}\n\n"
        f"Std RGB\n"
        f"R={std_rgb[0]:.1f}\n"
        f"G={std_rgb[1]:.1f}\n"
        f"B={std_rgb[2]:.1f}"
    )

    plt.gca().text(
        1.02,
        0.95,
        stats_text,
        transform=plt.gca().transAxes,
        fontsize=11,
        verticalalignment='top',
        bbox=dict(
            facecolor='white',
            edgecolor='black',
            alpha=0.95
        )
    )

    plt.title(
        f"{name} Image Histogram Analysis",
        fontweight='bold'
    )

    plt.xlabel("Pixel Intensity")

    plt.ylabel("Pixel Frequency")

    plt.xlim([0,256])

    plt.grid(
        linestyle='--',
        alpha=0.3
    )

    plt.legend()

    plt.tight_layout()

    plt.savefig(
        f"{name}_Histogram.png",
        dpi=600,
        bbox_inches='tight'
    )

    plt.savefig(
        f"{name}_Histogram.pdf",
        bbox_inches='tight'
    )

    plt.show()

from skimage.measure import shannon_entropy
import pandas as pd

rows = []

for name,img in images.items():

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2GRAY
    )

    rows.append([
        name,
        np.mean(gray),
        np.std(gray),
        shannon_entropy(gray)
    ])

df = pd.DataFrame(
    rows,
    columns=[
        "Transformation",
        "Mean",
        "Std",
        "Entropy"
    ]
)

print(df)

df.to_csv(
    "Dataset_Statistics.csv",
    index=False
)

import cv2
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams.update({
    "font.size":14
})

for name, img in images.items():

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2GRAY
    )

    fft = np.fft.fft2(gray)

    fft_shift = np.fft.fftshift(fft)

    magnitude = np.log(
        np.abs(fft_shift) + 1
    )

    mean_fft = np.mean(magnitude)
    std_fft = np.std(magnitude)

    plt.figure(figsize=(8,6))

    plt.imshow(
        magnitude,
        cmap='inferno'
    )

    plt.colorbar(
        fraction=0.046,
        pad=0.04
    )

    plt.title(
        f"{name} Frequency Spectrum",
        fontsize=18,
        fontweight='bold'
    )

    plt.axis('off')

    plt.savefig(
        f"{name}_FFT.png",
        dpi=600,
        bbox_inches='tight'
    )

    plt.savefig(
        f"{name}_FFT.pdf",
        bbox_inches='tight'
    )

    plt.show()

    print(
        f"{name}: Mean FFT={mean_fft:.3f}, "
        f"Std FFT={std_fft:.3f}"
    )

import cv2
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))

colors = {
    "Original":"#1f77b4",
    "Crop":"#2ca02c",
    "Compression":"#ff7f0e",
    "Screenshot":"#9467bd",
    "Text Overlay":"#d62728",
    "Noise":"#8c564b"
}

for name,img in images.items():

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2GRAY
    )

    hist = cv2.calcHist(
        [gray],
        [0],
        None,
        [256],
        [0,256]
    )

    plt.plot(
        hist,
        linewidth=3,
        label=name,
        color=colors[name]
    )

plt.title(
    "Pixel Intensity Distribution Across Transformations",
    fontsize=18,
    fontweight='bold'
)

plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "Pixel_Distribution_Comparison.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

from skimage.metrics import structural_similarity as ssim
import seaborn as sns
import pandas as pd

names = list(images.keys())

ssim_matrix = []

for n1 in names:

    row = []

    img1 = cv2.cvtColor(
        images[n1],
        cv2.COLOR_RGB2GRAY
    )

    for n2 in names:

        img2 = cv2.cvtColor(
            images[n2],
            cv2.COLOR_RGB2GRAY
        )

        score = ssim(
            img1,
            img2
        )

        row.append(score)

    ssim_matrix.append(row)

df = pd.DataFrame(
    ssim_matrix,
    index=names,
    columns=names
)

plt.figure(figsize=(8,6))

sns.heatmap(
    df,
    annot=True,
    fmt=".3f",
    cmap="YlGnBu"
)

plt.title(
    "Pairwise SSIM Similarity Matrix",
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()

plt.savefig(
    "SSIM_Heatmap.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

!pip install transformers

from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

model = CLIPModel.from_pretrained(
    "openai/clip-vit-base-patch32"
).to(device)

processor = CLIPProcessor.from_pretrained(
    "openai/clip-vit-base-patch32"
)

embeddings = {}

for name, img in images.items():

    pil_img = Image.fromarray(img)

    inputs = processor(
        images=pil_img,
        return_tensors="pt"
    )

    inputs = {k:v.to(device) for k,v in inputs.items()}

    with torch.no_grad():

        vision_outputs = model.vision_model(
            pixel_values=inputs["pixel_values"]
        )

        feat = vision_outputs.pooler_output

        feat = feat / feat.norm(
            dim=-1,
            keepdim=True
        )

        feat = feat.squeeze().cpu().numpy()

    embeddings[name] = feat

print("Done")
print("Embedding dimension =", feat.shape)

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

names = list(embeddings.keys())

matrix = np.zeros(
    (len(names), len(names))
)

for i,n1 in enumerate(names):
    for j,n2 in enumerate(names):

        matrix[i,j] = np.dot(
            embeddings[n1],
            embeddings[n2]
        )

df = pd.DataFrame(
    matrix,
    index=names,
    columns=names
)

plt.figure(figsize=(8,6))

sns.heatmap(
    df,
    annot=True,
    fmt=".4f",
    cmap="RdYlGn",
    square=True
)

plt.title(
    "CLIP Embedding Similarity Matrix",
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()

plt.savefig(
    "CLIP_Similarity_Heatmap.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

names = list(embeddings.keys())

X = np.array(
    [embeddings[n] for n in names]
)

tsne = TSNE(
    n_components=2,
    perplexity=5,
    random_state=42
)

coords = tsne.fit_transform(X)

plt.figure(figsize=(10,8))

colors = [
    "#1f77b4",
    "#2ca02c",
    "#ff7f0e",
    "#9467bd",
    "#d62728",
    "#8c564b"
]

for i,name in enumerate(names):

    plt.scatter(
        coords[i,0],
        coords[i,1],
        s=400,
        color=colors[i]
    )

    plt.annotate(
        name,
        (coords[i,0],coords[i,1]),
        fontsize=12,
        fontweight='bold'
    )

plt.title(
    "t-SNE Projection of CLIP Embeddings",
    fontsize=18,
    fontweight='bold'
)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "TSNE_CLIP.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

from skimage.metrics import structural_similarity
from skimage.metrics import peak_signal_noise_ratio
from skimage.measure import shannon_entropy
import pandas as pd

orig = cv2.cvtColor(
    images["Original"],
    cv2.COLOR_RGB2GRAY
)

rows = []

for name,img in images.items():

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_RGB2GRAY
    )

    if name == "Original":
        continue

    ssim_score = structural_similarity(
        orig,
        gray
    )

    psnr_score = peak_signal_noise_ratio(
        orig,
        gray
    )

    entropy_score = shannon_entropy(
        gray
    )

    rows.append([
        name,
        ssim_score,
        psnr_score,
        entropy_score
    ])

df = pd.DataFrame(
    rows,
    columns=[
        "Transformation",
        "SSIM",
        "PSNR",
        "Entropy"
    ]
)

print(df.round(4))

df.to_csv(
    "Image_Quality_Metrics.csv",
    index=False
)

!pip install transformers -q

from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = AutoImageProcessor.from_pretrained(
    "facebook/dinov2-base"
)

model = AutoModel.from_pretrained(
    "facebook/dinov2-base"
).to(device)

model.eval()

dino_embeddings = {}

for name,img in images.items():

    pil_img = Image.fromarray(img)

    inputs = processor(
        images=pil_img,
        return_tensors="pt"
    )

    inputs = {k:v.to(device) for k,v in inputs.items()}

    with torch.no_grad():

        outputs = model(**inputs)

        feat = outputs.last_hidden_state[:,0,:]

        feat = feat / feat.norm(
            dim=-1,
            keepdim=True
        )

        feat = feat.squeeze().cpu().numpy()

    dino_embeddings[name] = feat

print("DINO Embeddings Generated")
print("Dimension:", feat.shape)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

names = list(dino_embeddings.keys())

matrix = np.zeros(
    (len(names),len(names))
)

for i,n1 in enumerate(names):

    for j,n2 in enumerate(names):

        matrix[i,j] = np.dot(
            dino_embeddings[n1],
            dino_embeddings[n2]
        )

df = pd.DataFrame(
    matrix,
    index=names,
    columns=names
)

plt.figure(figsize=(8,6))

sns.heatmap(
    df,
    annot=True,
    fmt=".4f",
    cmap="RdYlGn",
    square=True
)

plt.title(
    "DINO Similarity Matrix",
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()

plt.savefig(
    "DINO_Heatmap.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

names = list(dino_embeddings.keys())

X = np.array(
    [dino_embeddings[n] for n in names]
)

tsne = TSNE(
    n_components=2,
    perplexity=5,
    random_state=42
)

coords = tsne.fit_transform(X)

plt.figure(figsize=(10,8))

colors = [
    "#1f77b4",
    "#2ca02c",
    "#ff7f0e",
    "#9467bd",
    "#d62728",
    "#8c564b"
]

for i,name in enumerate(names):

    plt.scatter(
        coords[i,0],
        coords[i,1],
        s=500,
        color=colors[i],
        edgecolors='black',
        linewidth=2
    )

    plt.annotate(
        name,
        (coords[i,0],coords[i,1]),
        fontsize=12,
        fontweight='bold'
    )

plt.title(
    "t-SNE Projection of DINO Embeddings",
    fontsize=18,
    fontweight='bold'
)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "DINO_TSNE.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

from sklearn.decomposition import PCA

pca = PCA(
    n_components=2
)

coords = pca.fit_transform(X)

plt.figure(figsize=(10,8))

for i,name in enumerate(names):

    plt.scatter(
        coords[i,0],
        coords[i,1],
        s=500,
        color=colors[i],
        edgecolors='black'
    )

    plt.annotate(
        name,
        (coords[i,0],coords[i,1]),
        fontsize=12,
        fontweight='bold'
    )

plt.title(
    "PCA Projection of DINO Embeddings",
    fontsize=18,
    fontweight='bold'
)

plt.xlabel(
    f"PC1 ({pca.explained_variance_ratio_[0]*100:.2f}%)"
)

plt.ylabel(
    f"PC2 ({pca.explained_variance_ratio_[1]*100:.2f}%)"
)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "DINO_PCA.png",
    dpi=600,
    bbox_inches='tight'
)

plt.show()

import pandas as pd

rows = []

original = dino_embeddings["Original"]

for name,emb in dino_embeddings.items():

    if name == "Original":
        continue

    similarity = np.dot(
        original,
        emb
    )

    rows.append([
        name,
        similarity
    ])

df = pd.DataFrame(
    rows,
    columns=[
        "Transformation",
        "Cosine Similarity"
    ]
)

print(df.sort_values(
    "Cosine Similarity",
    ascending=False
).round(4))

import pandas as pd
import numpy as np

original = embeddings["Original"]

rows = []

for name, emb in embeddings.items():

    similarity = np.dot(
        original,
        emb
    )

    rows.append([
        name,
        round(float(similarity),4)
    ])

clip_df = pd.DataFrame(
    rows,
    columns=[
        "Transformation",
        "CLIP Similarity"
    ]
)

print(clip_df)

clip_df.to_csv(
    "CLIP_Similarities.csv",
    index=False
)

import pandas as pd
import numpy as np

original = dino_embeddings["Original"]

rows = []

for name, emb in dino_embeddings.items():

    similarity = np.dot(
        original,
        emb
    )

    rows.append([
        name,
        round(float(similarity),4)
    ])

dino_df = pd.DataFrame(
    rows,
    columns=[
        "Transformation",
        "DINO Similarity"
    ]
)

print(dino_df)

dino_df.to_csv(
    "DINO_Similarities.csv",
    index=False
)

final_df = clip_df.merge(
    dino_df,
    on="Transformation"
)

print(final_df)

final_df.to_csv(
    "Semantic_Similarity_Summary.csv",
    index=False
)